/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.siatex.image.compress;

import java.util.LinkedHashSet;
import java.util.Set;

/**
 *
 * @author Apon
 */
public class RenameTexts extends javax.swing.JFrame {

    Main App;

    /**
     * Creates new form RenameTexts
     */
    public RenameTexts(Main app) {
        this.App = app;
        WindowIconSetter.setIcon(this);
        setDefaultCloseOperation(RenameTexts.DISPOSE_ON_CLOSE);
        initComponents();

        // Restore saved data if it exists
        if (this.App.getSavedData().length > 0) {
            StringBuilder sb = new StringBuilder();
            for (String line : this.App.getSavedData()) {
                sb.append(line).append("\n");
            }
            textArea.setText(sb.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        FilterBtn = new javax.swing.JButton();
        applyBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rename Text with new line seperate");
        setName("renameTxtWindow"); // NOI18N
        setType(java.awt.Window.Type.UTILITY);

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        FilterBtn.setText("Filter");
        FilterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterBtnActionPerformed(evt);
            }
        });

        applyBtn.setBackground(new java.awt.Color(0, 204, 204));
        applyBtn.setForeground(new java.awt.Color(255, 255, 255));
        applyBtn.setText("Apply");
        applyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(applyBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FilterBtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(applyBtn)
                    .addComponent(FilterBtn))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FilterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterBtnActionPerformed
        String[] lines = textArea.getText().split("\\n");
        Set<String> uniqueLines = new LinkedHashSet<>(); // Maintain order and uniqueness

        for (String line : lines) {
            uniqueLines.add(line.trim()); // Optionally, trim the lines to avoid "duplicate" entries with extra spaces
        }

        // Update the JTextArea with filtered unique lines
        StringBuilder filteredText = new StringBuilder();
        for (String line : uniqueLines) {
            filteredText.append(line).append("\n");
        }
        textArea.setText(filteredText.toString());
    }//GEN-LAST:event_FilterBtnActionPerformed

    private void applyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyBtnActionPerformed
        // Get lines from the JTextArea and store them in the main app's savedData array
        this.App.setSavedData(textArea.getText().split("\\n"));

        this.App.setRenameCount();
        // Close the supporting window
        this.dispose();
    }//GEN-LAST:event_applyBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FilterBtn;
    private javax.swing.JButton applyBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
